spin_manifest_version = 2

[application]
name = "advent-of-spin-2024"
version = "0.1.0"
authors = ["Davide Briani"]
description = ""

[[trigger.http]]
route = "/index.html"
component = "frontend"

[[trigger.http]]
route = "/api/..."
component = "api"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets", destination = "/" }]

[component.api]
source = "api/target/wasm32-wasip1/release/api.wasm"
key_value_stores = ["default"]

[component.api.build]
command = "cargo build --target wasm32-wasip1 --release --manifest-path api/Cargo.toml"
watch = ["api/src/**/*.rs", "api/Cargo.toml"]
